### ISSUE TITLE
404 using callback URL

### ISSUE THREAD

**Issue by tedder** [gocd-contrib/github-oauth-authorization-plugin#10]
I have the following for a callback URL:

    https://my.server.domain.com:8154/go/plugin/cd.go.authorization.github/authenticate

After a user auths with github, it tries to redirect them to: (with a real code)

    https://my.server.domain.com:8154/go/plugin/cd.go.authorization.github/authenticate?code=abcdef

That results in a 404.

**Comment by AienTech** [comment]
any news on this issue?

**Comment by chadlwilson** [comment]
I assume this isn't relevant now, so closing.
