### ISSUE TITLE
Instructions to configure plugin via automation

### ISSUE THREAD

**Issue by abdulg** [gocd-contrib/github-oauth-authorization-plugin#15]
I want to be able to create the required entries in the cruise-config.xml file. The entries created via the manual process have encrypted the sensitive data. How can I emulate that?

**Comment by ketan** [comment]
You'd use the [auth config api](https://api.gocd.org/current/#authorization-configuration) in conjunction with the [plugin info api](https://api.gocd.org/current/#plugin-info). The plugin info api will contain details about what form fields to submit for each plugin, the plugins settings api will accept the form configuration data.

For encryption, you can submit clear text values, which get encrypted on the server, or use the [encryption api](https://api.gocd.org/current/#encryption) to get encrypted values that can be submitted to the auth config api.
