### ISSUE TITLE
Instructions on enable plugin debug

### ISSUE THREAD

**Issue by yikaus** [gocd-contrib/github-oauth-authorization-plugin#16]
Currently configuring github oauth plugin with no luck, plugin able to configure on UI , however seems not triggering authenticate during login, additionally not able to see useful debug log to tracking down the issue , tried adding 

`plugin.cd.go.authorization.github.log.level=debug` on docker ENV

OR 

`<logger name="cd.go.authorization.github" level="DEBUG">` into logback-include.xml

None of above able to show debug log of plugin .

Can we add doc to describe adding debug log as well trouble shooting?

Kevin

**Comment by ketan** [comment]
@yikaus — I believe you may need to set the environment `GO_SERVER_SYSTEM_PROPERTIES=-D plugin.cd.go.authorization.github.log.level=debug` instead.

**Comment by yikaus** [comment]
Yeah , it works 

Thanks
