### ISSUE TITLE
Deprecated Teams API Endpoints

### ISSUE THREAD

**Issue by pedrocarrico** [gocd-contrib/github-oauth-authorization-plugin#193]
Hi,

I'm assigning roles by github teams with this plugin and seems that this plugin is being currently affected by a current brownout.

See https://github.blog/changelog/2022-02-22-sunset-notice-deprecated-teams-api-endpoints/

I believe this will eventually be taken care of but the github api library (ref: https://github.com/hub4j/github-api/issues/1386)

Cheers

**Comment by chadlwilson** [comment]
Hi there - are you able to help report 

- any stacktraces from the plugin logs to show which GoCD functionality was/is affected
- confirm the version of the plugin you are using
- confirm the configuration you are using (redacted if necessary, for the Authorization and the Roles) that should be able to replicate this
 
This information will make it easier to test from GoCD perspective, even if we are dependent on a change in the API library. Looks like maybe just the below, but would be good to confirm

https://github.com/gocd-contrib/github-oauth-authorization-plugin/blob/6bbb2b6e85d4f5740867432eb1c2dd62500ab75c/src/main/java/cd/go/authorization/github/MembershipChecker.java#L76-L93

**Comment by pedrocarrico** [comment]
hi @chadlwilson 

Right now I won't be able to replicate because the brownout from Github only lasted for 12h starting on 2pm UTC yesterday.

> - any stacktraces from the plugin logs to show which GoCD functionality was/is affected

There's no errors or stack traces (but I was running with no debug) but what happened was that users were not assigned to their correspondent roles in their team.

What I saw in the logs before the brownout was this:

```
[MembershipChecker] User `<redacted>` is a member of `<redacted>` organization.
2022-03-01 12:07:22,743 INFO  [qtp1382469079-25] GitHubPlugin:72 - [Authenticate] User `<redacted>` authenticated successfully.
2022-03-01 12:07:23,440 INFO  [qtp1382469079-25] GitHubPlugin:72 - [MembershipChecker] User `<redacted>` is a member of `developers` team.
```

And during the brownout:
```
2022-03-01 15:41:22,338 INFO  [qtp1382469079-26] GitHubPlugin:72 - [MembershipChecker] User `<redacted>` is a member of `<redacted>` organization.
2022-03-01 15:41:22,344 INFO  [qtp1382469079-26] GitHubPlugin:72 - [Authenticate] User `<redacted>` authenticated successfully.
```

>  - confirm the version of the plugin you are using

I'm using the latest version in the releases page (version `3.2.0-135`).

>  - confirm the configuration you are using (redacted if necessary, for the Authorization and the Roles) that should be able to replicate this

Just configured the specific team for the role to apply like in this screenshot (organization is redacted):
![Screenshot 2022-03-02 at 12 34 20](https://user-images.githubusercontent.com/151290/156362644-8924c565-e3d7-4b6d-b26a-caffaabec201.png)

Yup, it also seems to me that this plugin is just dependent from a change in the API library as well.

Thanks for helping out.

**Comment by chadlwilson** [comment]
Right, ok thanks, that's helpful!

Perhaps no logs because it's only the `team.hasMember` check that is failing. The way that code is written inside the API I think it just catches all exceptions and assumes false regardless of cause.

**Comment by chadlwilson** [comment]
https://build.gocd.org also uses this plugin so if I remember I can check for our use case during the next brownout on the 8th as well (assuming the API isn't fixed by then!). Looks like we use roughly the same (simple) config as yours.

**Comment by chadlwilson** [comment]
See [v3.3.0-146](https://github.com/gocd-contrib/github-oauth-authorization-plugin/releases/tag/v3.3.0-146) - new API version seems to work fine.

**Comment by chadlwilson** [comment]
https://github.blog/changelog/2022-03-04-paused-sunset-of-deprecated-teams-api-endpoints/ FWIW. Sigh :-)

**Comment by chadlwilson** [comment]
Feel free to use the Google Groups at https://groups.google.com/forum/#!forum/go-cd or GitHub discussions at https://github.com/gocd/gocd/discussions if it's general questions potentially of relevance to others.
