### ISSUE TITLE
Once install the plugin, doesn't show GitHub login page

### ISSUE THREAD

**Issue by seungweonpark** [gocd-contrib/github-oauth-authorization-plugin#241]
I have installed GoCD in Ubuntu 22.04 with https://docs.gocd.org/current/installation/install/agent/linux.html
After confirmed the go-server is up and running, and copy the github-oauth-authorization plugin into /var/lib/go-server/plugin/external  and restarted the go-server (https://github.com/gocd-contrib/github-oauth-authorization-plugin/blob/master/INSTALL.md)

```
root@at09-02-wp:/var/lib/go-server/plugins/external# ls -al
total 5804
drwxr-xr-x 2 go   go      4096 Oct 21 16:43 .
drwxr-xr-x 4 go   go      4096 Oct 21 14:03 ..
-rw-r--r-- 1 root root 5931421 Oct 21 16:43 github-oauth-authorization-plugin-3.3.1-213.jar
root@at09-02-wp:/var/lib/go-server/plugins/external#
```

Once I followed the **third step**(https://github.com/gocd-contrib/github-oauth-authorization-plugin/blob/master/INSTALL.md#create-authorization-configuration),  The web browser redirected to  `https://github.com/example/login/oauth/authorize?client_id=11515af105f2a5c3bb02&redirect_uri=http%3A%2F%2Fat09-02-wp.example.com%3A8153%2Fgo%2Fplugin%2Fcd.go.authorization.github%2Fauthenticate&scope=user%3Aemail` when accessing the same GoCD server in order to proceed to the 4th step, the log shows that 

```
root@at09-02-wp:/var/lib/go-server/plugins/external# tail -f /var/log/go-server/plugin-cd.go.authorization.github.log
2022-10-21 14:28:01,159 DEBUG [qtp363376992-41] GitHubPlugin:46 - [Get Authorization Server URL] Getting authorization server url from auth config.
2022-10-21 14:30:07,302 WARN  [Thread-79] GitHubPlugin:97 - Request go.plugin-settings.get-configuration is not supported by plugin.
2022-10-21 14:35:41,201 DEBUG [qtp308485422-42] GitHubPlugin:46 - [Get Authorization Server URL] Getting authorization server url from auth config.
```
and the web browser is stuck at the GitHub's 404 page with above redirected URL.

I think it used Client ID as putting in the third step, but it doesn't pop the login page.  This is what I set in GitHub OAuth:
```
Homepage URL: http://at09-02-wp.example.com:8153/go/pipelines
Authorization callback URL: https://at09-02-wp.example.com:8153/go/plugin/cd.go.authorization.github/authenticate
```
and from the 3rd step, I used the GitHub Enterprise with all fields.

```
GitHubEnterpriseUrl: https://github.com/example
ClientID: from GitHub OAuth
ClientSecret: from GitHub OAuth
Private Access Token: from GitHub OAuth
AllowedOrganizations: example

```
I am not sure if it's the known bug which it doesn't support GitHub Enterprise? Can you give a clue what's wrong with the config?

**Comment by chadlwilson** [comment]
I don't have a GitHub Enterprise instance to test with, but if you are getting a 404 on redirect to your instance, it's not getting as far as to actually use any of the authorization callback etc.

I don't understand what you actually configured for `GitHub Enterprise Url` - presumably not `https://github.com/example` and you've redacted the true value in the above? Unfortunately this is the part that seems most likely to be incorrect?

I'm confused at what you are trying to do though? Github Enterprise option is intended for the on-premise installation, as I understand. Is that what you're trying to set up?

**Comment by seungweonpark** [comment]
Thank you for the reply. my work has on-premise installation so that I used the GitHub Enterprise URL which I am not sure where I can get this from. However, when using regular Github, test connection seems to pass as you see the [video](https://youtu.be/BmyHIGI5Ewo). I think I put the correct information. please let me know if there is something wrong?

**Comment by chadlwilson** [comment]
Sorry for the slow reply - missed this one.

I'm confused, from the video it looks like normal github.com not an on-premise GitHub Enterprise installation. But anyway, that seems not highly relevant.

Your authorization callback URL registered in GitHub seems to have HTTPS in it, but your server doesn't seem to have HTTPS in front of it - seems you are accessing it via HTTP. The error is/was caused by this. When GitHub redirects to your GoCD server after authentication, it needs to have the correct URL registered.
