### ISSUE TITLE
Update installation guide for plugin

### ISSUE THREAD

**Issue by bdpiprava** [gocd-contrib/github-oauth-authorization-plugin#5]
Plugin installation guide need to be updated(with screenshots) with latest release of plugin.

**Comment by LaoLiulaoliu** [comment]
Hi @bdpiparva , I would like to ask where is the new guide? Have you posted it to some place? Thanks

**Comment by bdpiparva** [comment]
@LaoLiulaoliu - Here are instructions to setup the plugin https://github.com/gocd-contrib/github-oauth-authorization-plugin/blob/master/INSTALL.md

**Comment by ron-premier** [comment]
The plugin will not work with the version listed in the installation instructions (>=17.5?). See [the release notes for version 19.2](https://www.gocd.org/releases/#19-2-0). This plugin and two other authorization plugins were migrated to a new extension version that is incompatible with older versions.
