### ISSUE TITLE
When are changed emails synchronized into gocd?

### ISSUE THREAD

**Issue by voidus** [gocd-contrib/github-oauth-authorization-plugin#69]
Given that a user has an account in github and logged in to gocd and then changes their email address in github after that, when is this change synchronized to GoCD?

If this is in any way influenced by github-oauth-authorization-plugin, this should be documented in the README

**Comment by maheshp** [comment]
https://github.com/gocd/gocd/pull/6833 changes will update the `Email` and `Displayname` only if changed. These changes will be available in GoCD 19.8.0.

**Comment by voidus** [comment]
Should this be mentioned in the documentation? If yes, I could prepare a pull request. If not, this issue can be closed.

**Comment by arvindsv** [comment]
@voidus Yes, I think a PR would be nice. Thank you so much!

**Comment by rajiesh** [comment]
Verified on 19.8.0 (9912-33898b3adaf72cedea1604882d3554fd586571a8)
