### ISSUE TITLE
Document how to use plain values in cruise-config.xml

### ISSUE THREAD

**Issue by voidus** [gocd-contrib/github-oauth-authorization-plugin#75]
Hi 👋 

We're trying to have our GoCD server configured in code, ideally with a templated cruise-config.xml. This means we cannot use the encryption key generated by GoCD. 
We are templating cruise-config like this:

```
<property>
  <key>ClientId</key>
  <value>{{ env "GOCD_GITHUB_OAUTH_CLIENT_ID" }}</value>
</property>
```

but as far as I can tell, the plugin assumes the value is encrypted and fails to start.

I am aware that we would probably be able to pin the key, but I would prefer if we could set these values plainly in the config.

Thank you.

**Comment by tomzo** [comment]
Hi @voidus,
I would advice against trying to template the cruise-config.xml. This always ends up being a PITA. You could end up with weird concurrency issues and changes being lost. It's not recommended by GoCD team neither, the API was created to introduce changes to the server's config.

To change the settings of any plugin you could use the [API create or update call](https://api.gocd.org/current/#update-plugin-settings) after server is started.

Still, if you insist on going the templating route, then it would be still possible to encrypt the variable by reading the AES cipher key from file, encrypting the value with something like openssl, and then setting that in the `<value>{{ env "GOCD_GITHUB_OAUTH_CLIENT_ID" }}</value>`.
There is definitely no way to set it in plain text. If that's defined as secure variable, then it must be encrypted.

**Comment by voidus** [comment]
Hi tomzo, thank you for your answer.

We've had a talk about this and will try to migrate away from the templated file as you suggested.
