### ISSUE TITLE
Deprecated Github Auth Mechanism

### ISSUE THREAD

**Issue by adzuci** [gocd-contrib/github-oauth-authorization-plugin#98]
Hey there!

  It looks like Github has announced that they will no longer support passing `clientId()` and `clientSecret()` as query parameters and instead recommends they be passed in as a header.

https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters

  Would it be possible to update the following function to reflect this change?
https://github.com/gocd-contrib/github-oauth-authorization-plugin/blob/master/src/main/java/cd/go/authorization/github/executors/FetchAccessTokenRequestExecutor.java#L86

**Comment by bdpiparva** [comment]
Yes, It would be possible. Would you mind submitting PR for the same?
